name: Action on Pull Request to generate Kong Config from Spec and Validate it

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Generate Kong config from Spec and Validate config
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: inso export spec 'Dino Park' -o dinopark.yaml --ci
        name: Export Dino Park spec  
      - name: Generate Kong declarative configuration from Spec
        run: inso generate config dinopark.yaml -o kong-new.yaml --tags gitops --ci 
      - name: Convert configuration for 3.0
        run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong-new.yaml --output-file kong3.x.yaml
      - name: Validate Kong declarative configuration
        run: deck validate -s kong3.x.yaml